<div data-mage-init='{"hello": {"message": "You clicked!"}}'>
    <div id="clk"> CLICK HERE <div>
</div>


<div>
    <a href="#" class="action" title="Open Customer Login"
    data-mage-init='{"popupWindow": {
            "windowURL": "/customer/account/login",
            "windowName": "customer-login",
            "width": 400,
            "height": 400,
            "left": 0,
            "top": 0,
            "resizable": 1,
            "scrollbars": 1,
            "status": 1,
            "menubar": 1
        }}'>
        <span>PopupWindow widget</span>
    </a>
</div>


