<div data-mage-init='{"hello": {"message": "You clicked!"}}'>
    <div id="clk"> CLICK HERE <div>
</div>


<div>
    <a href="#" class="action" title="Open Customer Login"
    data-mage-init='{"popupWindow": {
            "windowURL": "/customer/account/login",
            "windowName": "customer-login",
            "width": 400,
            "height": 400,
            "left": 0,
            "top": 0,
            "resizable": 1,
            "scrollbars": 1,
            "status": 1,
            "menubar": 1
        }}'>
        <span>PopupWindow widget</span>
    </a>
</div>



<div id='popup-modal'>
        <h1> Hi I'm here.... </h1>
    </div>
    <script>
        require(
            [
                'jquery',
                'Magento_Ui/js/modal/modal'
            ],
            function(
                $,
                modal
            ) {
                var options = {
                    type: 'popup',
                    responsive: true,
                    innerScroll: true,
                    title: 'popup modal title',
                    buttons: [{
                        text: $.mage.__('Continue'),
                        class: '',
                        click: function () {
                            this.closeModal();
                        }
                    }]
                };
    
                var popup = modal(options, $('#popup-modal'));
    
                $('#popup-modal').modal('openModal');
            }
        );
    </script>

